# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(default='', max_length=36)),
                ('assignment_type', models.CharField(default='', max_length=5)),
                ('due_date', models.DateField(auto_now=True)),
                ('due_time', models.TimeField(auto_now=True)),
                ('expected_difficulty', models.IntegerField(default=0)),
                ('actual_difficulty', models.IntegerField(default=0)),
                ('expected_time', models.FloatField(default=0.0)),
                ('actual_time', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=0)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('prof_name', models.CharField(default='', max_length=36)),
                ('course_title', models.CharField(default='', max_length=36)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('assignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('professor_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ta_name', models.CharField(max_length=36)),
                ('office_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.OfficeHours')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('subtask_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('subtask_name', models.CharField(max_length=36)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
                ('office_hours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.OfficeHours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TeachingAssistant'),
        ),
    ]
