# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_studentassignment_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='base_assignment',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_assignment', to='backend.Assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
