# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171214_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='id',
            new_name='student_assignment_id',
        ),
    ]
