# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171215_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='percent_complete',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
    ]
