# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171216_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.CharField(default='', max_length=256, primary_key=True, serialize=False),
        ),
    ]
