# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171113_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('passwd', models.CharField(default='', max_length=36)),
            ],
        ),
    ]
