# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=36)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd_hash', models.CharField(default='', max_length=36)),
                ('role', models.CharField(default='', max_length=36)),
            ],
        ),
    ]
