# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwd_hash',
            new_name='passwd_hashs',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='user_names',
        ),
    ]
