# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171112_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='backend.Course'),
        ),
    ]
