# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171011_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='other',
        ),
    ]
