# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171112_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
                ('office_hours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.OfficeHours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='prof_name',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Course'),
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Course'),
        ),
        migrations.AddField(
            model_name='professor',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.TeachingAssistant'),
            preserve_default=False,
        ),
    ]
