# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171112_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=36)),
                ('role', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prof_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teaching_assistants',
        ),
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='backend.Assignment'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TeachingAssistant',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='backend.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', to='backend.User'),
        ),
    ]
