# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwd_hashs',
            new_name='passwd_hash',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_names',
            new_name='user_name',
        ),
    ]
