# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171011_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(default='', max_length=5)),
                ('professor_id', models.CharField(max_length=36)),
                ('due_date', models.DateField(auto_now=True)),
                ('due_time', models.TimeField(auto_now=True)),
                ('expected_difficulty', models.IntegerField(default=0)),
                ('actual_difficulty', models.IntegerField(default=0)),
                ('expected_time', models.FloatField(default=0.0)),
                ('actual_time', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=0)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=36)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('professor_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ta_name', models.CharField(max_length=36)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('subtask_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('subtask_name', models.CharField(max_length=36)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Assignment')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwd_hash',
            new_name='passwd',
        ),
        migrations.AddField(
            model_name='officehour',
            name='office_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.OfficeHours'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course'),
        ),
    ]
