# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171011_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(default='', max_length=5)),
                ('professor_id', models.CharField(max_length=36)),
                ('due_date', models.TimeField(auto_now=True)),
                ('expected_difficulty', models.IntegerField(default=0)),
                ('actual_difficulty', models.IntegerField(default=0)),
                ('expected_time', models.FloatField(default=0.0)),
                ('actual_time', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=0)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('subtask_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('subtask_name', models.CharField(max_length=36)),
                ('visible', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwd_hash',
            new_name='passwd',
        ),
    ]
