# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171112_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=36)),
                ('user_id', models.CharField(default='', max_length=36)),
            ],
        ),
    ]
