# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_coursestudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStudents',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='backend.User'),
        ),
    ]
